### ISSUE TITLE
ReadTagService service = new ReadTagService(requestPath); is not available

### ISSUE THREAD

**Issue by thomas-tran** [digitalpetri/ethernet-ip#19]
I followed the code for the logix server that connect to the ethernet/ip simulator and the code return the error

com.digitalpetri.enip.cip.CipResponseException: status=0x08 [service not supported] , additional=[]
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:63)
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:13)

**Comment by kevinherron** [comment]
What path did you use? Whatever you're connected to is reporting the object doesn't support that service.

**Comment by thomas-tran** [comment]
Hi kevinherron,

Here is the code

```
EtherNetIpClientConfig config = EtherNetIpClientConfig.builder("192.168.0.3")
        .setSerialNumber(0x00)
        .setVendorId(0x00)
        .setTimeout(Duration.ofSeconds(2))
        .setPort(44818)
        .build();

// Controller slot 0
PaddedEPath connectionPath = new PaddedEPath(
        new PortSegment(0, new byte[]{(byte) 0}));

CipClient client = new CipClient(config, connectionPath);

CipConnectionPool pool = new CipConnectionPool(2, client, connectionPath, 500);

// the tag we'll use as an example
PaddedEPath requestPath = new PaddedEPath(
        new AnsiDataSegment("tagFrequency"));

ReadTagService service = new ReadTagService(requestPath);

pool.acquire().whenComplete((connection, ex) -> {
    if (connection != null) {
        CompletableFuture<ByteBuf> f = client.invokeConnected(connection.getO2tConnectionId(), service);

        f.whenComplete((data, ex2) -> {
            if (data != null) {
                System.out.println("Tag data: " + ByteBufUtil.hexDump(data));
            } else {
                ex2.printStackTrace();
            }
            pool.release(connection);
        });
    } else {
        ex.printStackTrace();
    }
});
```

**Comment by kevinherron** [comment]
Okay, looks fine. The thing you're connected to is telling you the service isn't supported. Not sure there's much else to do.

**Comment by kevinherron** [comment]
Yes it's been tested with real Logix devices. This library is used in production in a commercial product.
