### ISSUE TITLE
PaddedEPath for Program Tag, Request Multiple Tags

### ISSUE THREAD

**Issue by wsuetholz** [digitalpetri/ethernet-ip#24]
Using the Logix ReadTagService and WriteTagService, how do I specify the path to a Program level tag.  I've attempted to use 'Program:Name.Tag' like inside Ignition, but that doesn't work.  I've also tried doing two AnsiDataSegments with the 'Name' and 'Tag'.

Is there a way to request retrieval/updating of multiple disparate tags?

Is there a better way to communicate about questions with this project other than opening issues?

**Comment by kevinherron** [comment]
Put "Program:ProgramName" in its own `AnsiDataSegment` before the rest of the segments. Make sure to include "Program:" prefix.

I typically don't like using GH issues for Q&A but since I haven't set up a mailing list for this project it's my own fault that they should land here :)

**Comment by kevinherron** [comment]
I missed this question:
> Is there a way to request retrieval/updating of multiple disparate tags?

Use [MultipleServicePacketService](https://github.com/digitalpetri/ethernet-ip/blob/53e8693d2076b58e129e8e0a67ecbb9b0b616976/cip-core/src/main/java/com/digitalpetri/enip/cip/services/MultipleServicePacketService.java).

**Comment by wsuetholz** [comment]
requestPath = new PaddedEPath(
                new DataSegment.AnsiDataSegment("Program:PressCell"),
                new
DataSegment.AnsiDataSegment("N_MeasSta_ThicknessMeasurement_Captured")
        );


com.digitalpetri.enip.cip.CipResponseException: status=0xFF, additional=[0x2105]
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:63)
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:13)
	at com.digitalpetri.enip.cip.CipClient.lambda$invokeConnected$0(CipClient.java:69)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.digitalpetri.enip.cip.CipClient$ConnectedDataHandler.itemsReceived(CipClient.java:249)
	at com.digitalpetri.enip.cip.CipClient.onUnitDataReceived(CipClient.java:218)
	at com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:168)
	at com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:34)
	at com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.digitalpetri.enip.cip.CipResponseException: status=0xFF, additional=[0x2105]
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:63)
	at com.digitalpetri.enip.logix.services.ReadTagService.decodeResponse(ReadTagService.java:13)
	at com.digitalpetri.enip.cip.CipClient.lambda$invokeConnected$0(CipClient.java:69)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.digitalpetri.enip.cip.CipClient$ConnectedDataHandler.itemsReceived(CipClient.java:249)
	at com.digitalpetri.enip.cip.CipClient.onUnitDataReceived(CipClient.java:218)
	at com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:168)
	at com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:34)
	at com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[image: image.png]

**Comment by wsuetholz** [comment]
Thank you for pointing that out..  I had code that was setting the
elementCount based upon the number of segments in the path.
