### ISSUE TITLE
unhandled item type: 0x86

### ISSUE THREAD

**Issue by holKow** [digitalpetri/ethernet-ip#43]
I send out ListIdentity command as broadcast to scan a network for devices. Usually every Ethernet/IP device is responding as expected. One customer has a device in its network that sends a response which can't be decoded.
When I call EnipPacket.decode(byteBuf) then I get The following exception:
java.io.IOException: java.util.concurrent.ExecutionException: io.netty.handler.codec.DecoderException: unhandled item type: 0x86
	at xxxx.scanEthernetIp(xxxx.java:526)
	at xxxx.scanNetwork(xxxx.java:347)
	at xxxx.scanNetwork(xxxx.java:240)
	at xxxx.lambda$scanNetwork$1(xxxx.java:734)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.netty.handler.codec.DecoderException: unhandled item type: 0x86
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at xxxx.scanEthernetIp(xxxx.java:524)
	... 4 more
Caused by: io.netty.handler.codec.DecoderException: unhandled item type: 0x86
	at com.digitalpetri.enip.cpf.CpfItem.decode(CpfItem.java:79)
	at com.digitalpetri.enip.cpf.CpfPacket.decode(CpfPacket.java:49)
	at com.digitalpetri.enip.commands.ListIdentity.decode(ListIdentity.java:54)
	at com.digitalpetri.enip.EnipPacket.decodeCommand(EnipPacket.java:163)
	at com.digitalpetri.enip.EnipPacket.decode(EnipPacket.java:127)
	at xxxx.receive(Scanner.java:65)
	at xxxx.scanNet(Scanner.java:32)
	at xxxx.scanAllNet(Scanner.java:42)
	at xxxx.scan(GlobalEthernetIpConnectionDevice.java:63)
	at xxxx.lambda$scanEthernetIp$2(xxxx.java:512)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

I could see that the response contains 2 CpfItem, a CipIdentityItem and an unknown one.
Here is the response as byte array:
[99, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 12, 0, 45, 0, 1, 0, 0, 2, -81, 18, -64, -88, -56, -7, 0, 0, 0, 0, 0, 0, 0, 0, 77, 0, 12, 0, 115, 0, 11, 1, 96, 0, -23, 27, -51, 44, 11, 82, 68, 78, 69, 84, 76, 84, 69, 69, 48, 55, -1, -122, 0, 5, 0, 2, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

I hope someone can help me with that issue.

**Comment by kevinherron** [comment]
Any chance you can get a Wireshark capture of this? 

I don't see a definition for this item type in the spec but it seems I should be ignoring unknown types if possible.

**Comment by pturmel** [comment]
That's the item type for CIP Security information, per my copy of the spec.

**Comment by kevinherron** [comment]
Maybe I should get a newer copy... mine is dated 2016.

**Comment by pturmel** [comment]
It first showed up in the November 2016 edition, v1.22.

**Comment by kevinherron** [comment]
Ahh, the definition is in the separate CIP Security Vol8, not Vol2 with the rest of the CPF items.

**Comment by kevinherron** [comment]
@holKow can you build and test https://github.com/digitalpetri/ethernet-ip/tree/issues/gh43 and report back?

**Comment by holKow** [comment]
I made a small unit test with the problematic response and it passed now. The rest of my software is still working. So we have a success.
I’ looking forward to the final version in mvnrepository.


Von: Kevin Herron <notifications@github.com>
Gesendet: Donnerstag, 1. Oktober 2020 21:04
An: digitalpetri/ethernet-ip <ethernet-ip@noreply.github.com>
Cc: Kowalschek, Holger <Holger.Kowalschek@flexlink.com>; Mention <mention@noreply.github.com>
Betreff: Re: [digitalpetri/ethernet-ip] unhandled item type: 0x86 (#43)


@holKow<https://urldefense.com/v3/__https:/github.com/holKow__;!!Mxbk5DQ!6uYL26dNd0FcMUa6pwlddjm3PulivRvWX8jRnTZ57Qjxt6v7QV11ITmmQ1T-7uqk0NzoA-HTMA$> can you build and test https://github.com/digitalpetri/ethernet-ip/tree/issues/gh43<https://urldefense.com/v3/__https:/github.com/digitalpetri/ethernet-ip/tree/issues/gh43__;!!Mxbk5DQ!6uYL26dNd0FcMUa6pwlddjm3PulivRvWX8jRnTZ57Qjxt6v7QV11ITmmQ1T-7uqk0NyYzGhBlA$> and report back?

**Comment by kevinherron** [comment]
Version 1.3.4 has been released and should be available in Maven Central.
