### ISSUE TITLE
Question about io.netty.channel.DefaultChannelPipeline onUnhandledInboundException logs

### ISSUE THREAD

**Issue by JensGabe** [digitalpetri/ethernet-ip#59]
I'm not sure where in the stack this goes wrong (My use of Ethernet-ip, in ethernet-ip, in Netty or ???).
But I'm getting many of these:
```
aug. 22, 2022 3:49:28 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
The setup has 4 PLC connections (2 using Milo and 2 using Ethernet/IP), so debugging Netty is a bit difficult.
I suspect it is something related to asynchrous tasks not being cleared on reconnect in Ethernet/IP, but I have nothing but a gut feeling to back this up, and the fact that it only happens when the Ethernet/IP connections start to "act up" (disconnects for some reason), which only happens on the production system ~2 times in a week, which does not make it specifically easy to debug, but the logs quickly fills up the harddrive.
Do you have any idea about where to start looking?

**Comment by JensGabe** [comment]
Sorry, I may have found it... 
Possible racing condition in initialization of some active polling, which could result in them not getting cancelled on reconnects.
