### ISSUE TITLE
ConnectionFailure for AllenBradley 1769-L33ER Controller with Firmware version 36

### ISSUE THREAD

**Issue by prasenjith-altizon** [digitalpetri/ethernet-ip#76]
After the Firmware upgrade from 20 to 36 AllenBradley 1769-L33ER Controller is not connecting and giving the below error. Before upgradation, it was connected.

Caused by: com.digitalpetri.enip.cip.CipResponseException: status=0x01 [connection failure] , additional=[0x0315]
	at com.digitalpetri.enip.cip.services.ForwardOpenService.decodeResponse(ForwardOpenService.java:50)
	at com.digitalpetri.enip.cip.CipConnectionPool$DefaultConnectionFactory.lambda$forwardOpen$0(CipConnectionPool.java:214)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.digitalpetri.enip.cip.CipClient.lambda$sendUnconnectedData$8(CipClient.java:212)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.digitalpetri.enip.EtherNetIpClient$PendingRequest.lambda$new$0(EtherNetIpClient.java:311)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:189)
	at com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:38)
	at com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

Getting above error while using ConnectionPool. For connectionPath I'm trying : 
```
public static final PaddedEPath connectionPath = new EPath.PaddedEPath(new PortSegment(1, new byte[] {(byte) 0}));
public static final EPath.PaddedEPath connectionPath = new EPath.PaddedEPath(Collections.emptyList());
```
Still getting the same error.

**Comment by kevinherron** [comment]
Sounds similar to [this issue](https://github.com/digitalpetri/ethernet-ip/discussions/62), where the problem ending up being that they were not configuring a vendor ID.
